# Generated by Django 4.1.10 on 2023-08-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='utilisateur',
        ),
    ]
