# Generated by Django 4.1.10 on 2023-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formulaire_utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('sexe', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=6)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('sport', models.BooleanField()),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='utilisateur',
        ),
    ]
