# Generated by Django 4.1.10 on 2023-08-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0004_formulaire_utilisateur_delete_utilisateur'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formulaire_utilisateur',
            table='formulaire_utilisateur',
        ),
    ]
