# Generated by Django 4.1.10 on 2023-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0005_alter_formulaire_utilisateur_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire_utilisateur',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
