# Generated by Django 4.1.10 on 2023-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0006_alter_formulaire_utilisateur_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire_utilisateur',
            name='sport',
        ),
        migrations.AddField(
            model_name='formulaire_utilisateur',
            name='qualification_chercheur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulaire_utilisateur',
            name='qualification_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
