# Generated by Django 4.1.10 on 2023-08-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('formulaire', '0009_alter_formulaire_utilisateur_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire_utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='auth.group', verbose_name='Groupes'),
        ),
        migrations.AlterField(
            model_name='formulaire_utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='auth.permission', verbose_name='Permissions'),
        ),
    ]
