# Generated by Django 4.1.10 on 2023-08-30 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0010_alter_formulaire_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulaire.formulaire_utilisateur'),
        ),
    ]
