# Generated by Django 4.1.10 on 2023-08-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0013_alter_formulaire_utilisateur_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire_utilisateur',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
