# Generated by Django 4.1.10 on 2023-08-30 02:20

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0016_alter_formulaire_utilisateur_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire_utilisateur',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
