# Generated by Django 4.1.10 on 2023-08-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0020_alter_formulaire_utilisateur_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire_utilisateur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
