# Generated by Django 4.1.10 on 2023-08-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0023_alter_formulaire_utilisateur_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire_utilisateur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='formulaire_utilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='formulaire_utilisateur',
            name='last_name',
        ),
    ]
