# Generated by Django 4.1.10 on 2023-08-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0026_alter_formulaire_utilisateurr_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire_utilisateurr',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
