# Generated by Django 4.1.10 on 2023-09-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0028_pharmaciedegarde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmaciedegarde',
            old_name='Localisation',
            new_name='localisation',
        ),
        migrations.RenameField(
            model_name='pharmaciedegarde',
            old_name='Pharmacie',
            new_name='pharmacie',
        ),
        migrations.RenameField(
            model_name='pharmaciedegarde',
            old_name='Plage',
            new_name='plage',
        ),
        migrations.RenameField(
            model_name='pharmaciedegarde',
            old_name='Téléphone1',
            new_name='téléphone1',
        ),
        migrations.RenameField(
            model_name='pharmaciedegarde',
            old_name='Téléphone2',
            new_name='téléphone2',
        ),
        migrations.RenameField(
            model_name='pharmaciedegarde',
            old_name='Téléphone3',
            new_name='téléphone3',
        ),
    ]
