# Generated by Django 4.1.10 on 2023-09-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0029_rename_localisation_pharmaciedegarde_localisation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmaciedegarde',
            old_name='téléphone1',
            new_name='telephone1',
        ),
        migrations.RenameField(
            model_name='pharmaciedegarde',
            old_name='téléphone2',
            new_name='telephone2',
        ),
        migrations.RenameField(
            model_name='pharmaciedegarde',
            old_name='téléphone3',
            new_name='telephone3',
        ),
    ]
